export const topicCatalog = [
  {
    id: "algebra",
    name: "Algebra",
    icon: "x",
    color: "violet",
    description: "Variables, equations and expressions",
    lessons: 12,
    progress: 78,
    level: "Moderate",
  },
  {
    id: "functions",
    name: "Functions",
    icon: "f",
    color: "blue",
    description: "Inputs, outputs, graphs and mappings",
    lessons: 10,
    progress: 45,
    level: "Beginner",
  },
  {
    id: "trigonometry",
    name: "Trigonometry",
    icon: "△",
    color: "orange",
    description: "Angles, triangles and periodic relations",
    lessons: 14,
    progress: 62,
    level: "Moderate",
  },
  {
    id: "differentiation",
    name: "Differentiation",
    icon: "d",
    color: "pink",
    description: "Rates of change, slopes and derivatives",
    lessons: 11,
    progress: 38,
    level: "Beginner",
  },
  {
    id: "integration",
    name: "Integration",
    icon: "∫",
    color: "green",
    description: "Areas, accumulation and antiderivatives",
    lessons: 13,
    progress: 85,
    level: "Advanced",
  },
  {
    id: "probability",
    name: "Probability",
    icon: "%",
    color: "yellow",
    description: "Chance, outcomes and uncertainty",
    lessons: 9,
    progress: 24,
    level: "Beginner",
  },
  {
    id: "statistics",
    name: "Statistics",
    icon: "▥",
    color: "cyan",
    description: "Data, distributions and inference",
    lessons: 10,
    progress: 0,
    level: "Beginner",
  },
];

export const lessons = {
  algebra: {
    concept: "Linear Equations",
    explanation:
      "A linear equation is a mathematical sentence where the highest power of the variable is one. Solving it means finding the value that makes both sides equal.",
    intuition:
      "Imagine a balance scale. Whatever you do to one side, you must also do to the other. If you remove 4 from the left, remove 4 from the right too.",
    example: "3x + 4 = 19",
    steps: [
      "Subtract 4 from both sides: 3x = 15",
      "Divide both sides by 3: x = 5",
      "Check: 3(5) + 4 = 19 ✓",
    ],
    practice: "Solve for x: 5x - 7 = 18",
    answer: "5",
  },
  functions: {
    concept: "Understanding Functions",
    explanation:
      "A function is a rule that gives exactly one output for every allowed input. We often write it as f(x), which means the output of f when the input is x.",
    intuition:
      "Think of a vending machine. You press one button as the input, the machine follows its rule, and gives one specific snack as the output.",
    example: "If f(x) = 2x + 3, find f(4)",
    steps: [
      "Replace x with 4: f(4) = 2(4) + 3",
      "Multiply: f(4) = 8 + 3",
      "Add: f(4) = 11",
    ],
    practice: "If f(x) = 3x - 2, find f(5)",
    answer: "13",
  },
  trigonometry: {
    concept: "The Sine Ratio",
    explanation:
      "In a right triangle, sine connects an angle to the ratio of the opposite side and the hypotenuse.",
    intuition:
      "As a ramp gets steeper, its vertical rise becomes a larger share of its full length. Sine measures that share.",
    example: "Opposite = 3, hypotenuse = 5. Find sin θ.",
    steps: ["Use sin θ = opposite / hypotenuse", "Substitute: sin θ = 3 / 5", "Therefore sin θ = 0.6"],
    practice: "Opposite = 8 and hypotenuse = 10. Find sin θ.",
    answer: "0.8",
  },
  differentiation: {
    concept: "The Power Rule",
    explanation:
      "A derivative measures how quickly a quantity changes. For x raised to a power, multiply by the power and reduce the power by one.",
    intuition:
      "A speedometer shows your rate of change of distance. A derivative is a mathematical speedometer for any changing quantity.",
    example: "Differentiate y = x³",
    steps: ["Bring the power 3 to the front", "Reduce the power by one", "dy/dx = 3x²"],
    practice: "Differentiate y = 4x³",
    answer: "12x^2",
  },
  integration: {
    concept: "Basic Integration",
    explanation:
      "Integration reverses differentiation. It combines tiny pieces to find a total, such as the area under a curve.",
    intuition:
      "Imagine filling a container one tiny layer at a time. Integration adds all those thin layers to find the total volume.",
    example: "Integrate ∫ 3x² dx",
    steps: ["Increase the power by one: x³", "Divide by the new power: 3x³ / 3", "Answer: x³ + C"],
    practice: "Integrate ∫ 2x dx",
    answer: "x^2+c",
  },
  probability: {
    concept: "Simple Probability",
    explanation:
      "Probability compares the number of desired outcomes with the total number of equally likely outcomes.",
    intuition:
      "A bag has five marbles and two are blue. Without looking, blue marbles represent two of your five possible picks.",
    example: "Find the probability of rolling an even number on a fair die.",
    steps: ["Even outcomes are 2, 4 and 6", "There are 3 desired outcomes out of 6", "Probability = 3/6 = 1/2"],
    practice: "What is the probability of rolling a number greater than 4 on a fair die?",
    answer: "1/3",
  },
  statistics: {
    concept: "The Arithmetic Mean",
    explanation:
      "The mean is a measure of center found by adding every value and dividing by the number of values.",
    intuition:
      "If everyone pooled their points and shared them equally, the amount each person received would be the mean.",
    example: "Find the mean of 4, 6, 8.",
    steps: ["Add the values: 4 + 6 + 8 = 18", "Count the values: 3", "Mean = 18 / 3 = 6"],
    practice: "Find the mean of 5, 7, 9, 11.",
    answer: "8",
  },
};

export const testQuestions = {
  algebra: [
    ["Solve: 2x + 6 = 16", "5"],
    ["Solve: 4x - 8 = 12", "5"],
    ["Simplify: 3(x + 2)", "3x+6"],
    ["Solve: 7x = 42", "6"],
    ["Solve: x / 4 = 3", "12"],
    ["Simplify: 2x + 5x", "7x"],
    ["Solve: 3x + 1 = 10", "3"],
    ["Expand: 2(3x - 1)", "6x-2"],
    ["Solve: 9 - x = 4", "5"],
    ["Simplify: x + x + x", "3x"],
  ],
  functions: [
    ["If f(x) = x + 7, find f(3)", "10"],
    ["If g(x) = 2x², find g(2)", "8"],
    ["If h(x) = 5 - x, find h(1)", "4"],
    ["If f(x) = 3x, find f(4)", "12"],
    ["If f(x) = x² + 1, find f(3)", "10"],
    ["If g(x) = 10 - 2x, find g(2)", "6"],
    ["If h(x) = x / 2, find h(8)", "4"],
    ["If f(x) = 4x + 1, find f(0)", "1"],
    ["If g(x) = x² - 4, find g(2)", "0"],
    ["If h(x) = 2x + 5, find h(5)", "15"],
  ],
  trigonometry: [
    ["Find sin θ when opposite = 6 and hypotenuse = 10", "0.6"],
    ["What is sin 30°?", "0.5"],
    ["Find cos θ when adjacent = 4 and hypotenuse = 5", "0.8"],
    ["What is cos 60°?", "0.5"],
    ["What is tan 45°?", "1"],
    ["Find sin θ when opposite = 5 and hypotenuse = 13", "5/13"],
    ["Find cos θ when adjacent = 12 and hypotenuse = 13", "12/13"],
    ["Find tan θ when opposite = 3 and adjacent = 4", "3/4"],
    ["What is sin 90°?", "1"],
    ["What is cos 0°?", "1"],
  ],
  differentiation: [
    ["Differentiate x²", "2x"],
    ["Differentiate 5x³", "15x^2"],
    ["Differentiate 7x", "7"],
    ["Differentiate x⁴", "4x^3"],
    ["Differentiate 3x²", "6x"],
    ["Differentiate 9", "0"],
    ["Differentiate 2x⁵", "10x^4"],
    ["Differentiate x³ + x", "3x^2+1"],
    ["Differentiate 4x² - 3", "8x"],
    ["Differentiate 6x⁴", "24x^3"],
  ],
  integration: [
    ["Integrate 4x dx", "2x^2+c"],
    ["Integrate 3x² dx", "x^3+c"],
    ["Integrate 5 dx", "5x+c"],
    ["Integrate 2x³ dx", "x^4/2+c"],
    ["Integrate x² dx", "x^3/3+c"],
    ["Integrate 6x² dx", "2x^3+c"],
    ["Integrate 8x³ dx", "2x^4+c"],
    ["Integrate x dx", "x^2/2+c"],
    ["Integrate 4 dx", "4x+c"],
    ["Integrate 5x⁴ dx", "x^5+c"],
  ],
  probability: [
    ["Probability of heads on a fair coin?", "1/2"],
    ["Probability of rolling a 6 on a fair die?", "1/6"],
    ["Probability of an odd number on a fair die?", "1/2"],
    ["Probability of tails on a fair coin?", "1/2"],
    ["Probability of rolling less than 3 on a fair die?", "1/3"],
    ["Probability of rolling an even number on a fair die?", "1/2"],
    ["Probability of drawing an ace from 52 cards?", "1/13"],
    ["Probability of an impossible event?", "0"],
    ["Probability of a certain event?", "1"],
    ["Probability of rolling greater than 2 on a fair die?", "2/3"],
  ],
  statistics: [
    ["Find the mean of 2, 4, 6", "4"],
    ["Find the median of 3, 8, 5", "5"],
    ["Find the range of 4, 9, 12", "8"],
    ["Find the mean of 10, 20, 30", "20"],
    ["Find the median of 2, 4, 6, 8, 10", "6"],
    ["Find the mode of 1, 2, 2, 3", "2"],
    ["Find the range of 5, 11, 14", "9"],
    ["Find the mean of 3, 3, 6", "4"],
    ["Find the median of 9, 1, 5", "5"],
    ["Find the mode of 4, 4, 6, 7", "4"],
  ],
};
